const data = {
  men: [
    {
      id: 1,
      name: "smthn1",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 2,
      name: "smthn2",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 3,
      name: "smthn3",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 4,
      name: "smthn4",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 5,
      name: "smthn5",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 6,
      name: "smthn6",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
  ],
  women: [
    {
      id: 7,
      name: "smthn7",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 8,
      name: "smthn8",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 9,
      name: "smthn9",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 10,
      name: "smthn10",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 11,
      name: "smthn11",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 12,
      name: "smthn12",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
  ],
  shoes: [
    {
      id: 13,
      name: "smthn13",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 14,
      name: "smthn14",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 15,
      name: "smthn15",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 16,
      name: "smthn16",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 17,
      name: "smthn17",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
    {
      id: 18,
      name: "smthn18",
      desc: "smthnsmthn",
      price: 1,
      img: "https://i.ibb.co/w7qfDTx/2.png",
      amount: 1,
    },
  ],
};

export default data;
